# Generated by Django 3.1.2 on 2020-11-16 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('age', models.CharField(blank=True, max_length=6, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('B', 'Blood'), ('U', 'Urine'), ('S', 'Self')], max_length=100)),
                ('price', models.FloatField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Referred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('designation', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(max_length=12)),
                ('comission_percent', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_total', models.FloatField(default=0)),
                ('others_charge', models.FloatField(default=0)),
                ('discount_amount', models.FloatField(default=0)),
                ('total_before_discount', models.FloatField(default=0)),
                ('total_after_discount', models.FloatField(default=0)),
                ('amount_paid', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('comission', models.FloatField(default=0)),
                ('total_after_comission', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('due_paid', models.FloatField(default=0)),
                ('duepaytimestamp', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathology.consumer')),
                ('ref_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathology.referred')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('value', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathology.item')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathology.consumer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='pathology.OrderItem')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathology.consumer')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathology.payment')),
            ],
        ),
        migrations.AddField(
            model_name='consumer',
            name='ReferredBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathology.referred'),
        ),
    ]
